name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (v12.22.12)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 12.22.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build the Angular project
    - name: Build Angular application
      run: npm run build -- --base-href "/"

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
